### ISSUE TITLE
sre-enriched mathml throws error

### ISSUE THREAD

**Issue by pkra** [mathjax/mj3-demos-node#5]
E.g., convert

```
\begin{align}\dot{x} & = \sigma(y-x) \\ \dot{y} & = \rho x - y - xz \\ \dot{z} & = -\beta z + xy\end{align}
```

to MathML using v3, then enrich it via SRE v3 to get

```
<math display="block" data-semantic-structure="(64 (19 (3 (2 0 1)) (18 (17 14 5 (16 6 15 (13 7 (12 8 9 10) 11))))) (41 (23 (22 20 21)) (40 (39 33 25 (36 (35 26 34 27) 28 29 30 (38 31 37 32))))) (63 (45 (44 42 43)) (62 (61 54 47 (60 (57 48 (56 49 55 50)) 51 (59 52 58 53))))))"><mtable displaystyle="true" columnalign="right left right left right left right left right left right left" columnspacing="0em 2em 0em 2em 0em 2em 0em 2em 0em 2em 0em" rowspacing="3pt" data-semantic-type="table" data-semantic-role="equality" data-semantic-id="64" data-semantic-children="19,41,63" data-semantic-speech="StartLayout 1st Row 1st Column ModifyingAbove x With dot 2nd Column equals sigma left-parenthesis y minus x right-parenthesis 2nd Row 1st Column ModifyingAbove y With dot 2nd Column equals rho x minus y minus x z 3rd Row 1st Column ModifyingAbove z With dot 2nd Column equals minus beta z plus x y EndLayout"><mtr data-semantic-type="row" data-semantic-role="table" data-semantic-id="19" data-semantic-children="3,18" data-semantic-parent="64" data-semantic-speech="1st Column ModifyingAbove x With dot 2nd Column equals sigma left-parenthesis y minus x right-parenthesis" data-semantic-prefix="1st Row"><mtd data-semantic-type="cell" data-semantic-role="table" data-semantic-id="3" data-semantic-children="2" data-semantic-parent="19" data-semantic-speech="ModifyingAbove x With dot" data-semantic-prefix="1st Column"><mrow class="MJX-TeXAtom-ORD"><mover data-semantic-type="overscore" data-semantic-role="latinletter" data-semantic-id="2" data-semantic-children="0,1" data-semantic-parent="3" data-semantic-speech="ModifyingAbove x With dot"><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="0" data-semantic-parent="2" data-semantic-speech="x" data-semantic-prefix="Base">x</mi><mo data-semantic-type="operator" data-semantic-role="overaccent" data-semantic-id="1" data-semantic-parent="2" data-semantic-speech="dot" data-semantic-prefix="Overscript">˙</mo></mover></mrow></mtd><mtd data-semantic-type="cell" data-semantic-role="table" data-semantic-id="18" data-semantic-children="17" data-semantic-parent="19" data-semantic-speech="equals sigma left-parenthesis y minus x right-parenthesis" data-semantic-prefix="2nd Column"><mi/><mrow data-semantic-type="relseq" data-semantic-role="equality" data-semantic-id="17" data-semantic-children="14,16" data-semantic-content="5" data-semantic-parent="18" data-semantic-speech="equals sigma left-parenthesis y minus x right-parenthesis"><mrow data-semantic-type="empty" data-semantic-role="unknown" data-semantic-id="14" data-semantic-parent="17" data-semantic-speech=""/><mo data-semantic-type="relation" data-semantic-role="equality" data-semantic-id="5" data-semantic-parent="17" data-semantic-operator="relseq,=" data-semantic-speech="equals">=</mo><mrow data-semantic-type="infixop" data-semantic-role="implicit" data-semantic-annotation="clearspeak:unit;clearspeak:unit" data-semantic-id="16" data-semantic-children="6,13" data-semantic-content="15" data-semantic-parent="17" data-semantic-speech="sigma left-parenthesis y minus x right-parenthesis"><mi data-semantic-type="identifier" data-semantic-role="greekletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="6" data-semantic-parent="16" data-semantic-speech="sigma">σ</mi><mo data-semantic-type="operator" data-semantic-role="multiplication" data-semantic-id="15" data-semantic-parent="16" data-semantic-added="true" data-semantic-operator="infixop,⁢" data-semantic-speech="times">⁢</mo><mrow data-semantic-type="fenced" data-semantic-role="leftright" data-semantic-id="13" data-semantic-children="12" data-semantic-content="7,11" data-semantic-parent="16" data-semantic-speech="left-parenthesis y minus x right-parenthesis"><mo stretchy="false" data-semantic-type="fence" data-semantic-role="open" data-semantic-id="7" data-semantic-parent="13" data-semantic-operator="fenced" data-semantic-speech="left-parenthesis">(</mo><mrow data-semantic-type="infixop" data-semantic-role="subtraction" data-semantic-id="12" data-semantic-children="8,10" data-semantic-content="9" data-semantic-parent="13" data-semantic-speech="y minus x"><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="8" data-semantic-parent="12" data-semantic-speech="y">y</mi><mo data-semantic-type="operator" data-semantic-role="subtraction" data-semantic-id="9" data-semantic-parent="12" data-semantic-operator="infixop,−" data-semantic-speech="minus">−</mo><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="10" data-semantic-parent="12" data-semantic-speech="x">x</mi></mrow><mo stretchy="false" data-semantic-type="fence" data-semantic-role="close" data-semantic-id="11" data-semantic-parent="13" data-semantic-operator="fenced" data-semantic-speech="right-parenthesis">)</mo></mrow></mrow></mrow></mtd></mtr><mtr data-semantic-type="row" data-semantic-role="table" data-semantic-id="41" data-semantic-children="23,40" data-semantic-parent="64" data-semantic-speech="1st Column ModifyingAbove y With dot 2nd Column equals rho x minus y minus x z" data-semantic-prefix="2nd Row"><mtd data-semantic-type="cell" data-semantic-role="table" data-semantic-id="23" data-semantic-children="22" data-semantic-parent="41" data-semantic-speech="ModifyingAbove y With dot" data-semantic-prefix="1st Column"><mrow class="MJX-TeXAtom-ORD"><mover data-semantic-type="overscore" data-semantic-role="latinletter" data-semantic-id="22" data-semantic-children="20,21" data-semantic-parent="23" data-semantic-speech="ModifyingAbove y With dot"><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="20" data-semantic-parent="22" data-semantic-speech="y" data-semantic-prefix="Base">y</mi><mo data-semantic-type="operator" data-semantic-role="overaccent" data-semantic-id="21" data-semantic-parent="22" data-semantic-speech="dot" data-semantic-prefix="Overscript">˙</mo></mover></mrow></mtd><mtd data-semantic-type="cell" data-semantic-role="table" data-semantic-id="40" data-semantic-children="39" data-semantic-parent="41" data-semantic-speech="equals rho x minus y minus x z" data-semantic-prefix="2nd Column"><mi/><mrow data-semantic-type="relseq" data-semantic-role="equality" data-semantic-id="39" data-semantic-children="33,36" data-semantic-content="25" data-semantic-parent="40" data-semantic-speech="equals rho x minus y minus x z"><mrow data-semantic-type="empty" data-semantic-role="unknown" data-semantic-id="33" data-semantic-parent="39" data-semantic-speech=""/><mo data-semantic-type="relation" data-semantic-role="equality" data-semantic-id="25" data-semantic-parent="39" data-semantic-operator="relseq,=" data-semantic-speech="equals">=</mo><mrow data-semantic-type="infixop" data-semantic-role="subtraction" data-semantic-id="36" data-semantic-children="35,29,38" data-semantic-content="28,30" data-semantic-parent="39" data-semantic-speech="rho x minus y minus x z"><mrow data-semantic-type="infixop" data-semantic-role="implicit" data-semantic-annotation="clearspeak:simple;clearspeak:unit;clearspeak:simple;clearspeak:unit" data-semantic-id="35" data-semantic-children="26,27" data-semantic-content="34" data-semantic-parent="36" data-semantic-speech="rho x"><mi data-semantic-type="identifier" data-semantic-role="greekletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="26" data-semantic-parent="35" data-semantic-speech="rho">ρ</mi><mo data-semantic-type="operator" data-semantic-role="multiplication" data-semantic-id="34" data-semantic-parent="35" data-semantic-added="true" data-semantic-operator="infixop,⁢" data-semantic-speech="times">⁢</mo><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="27" data-semantic-parent="35" data-semantic-speech="x">x</mi></mrow><mo data-semantic-type="operator" data-semantic-role="subtraction" data-semantic-id="28" data-semantic-parent="36" data-semantic-operator="infixop,−" data-semantic-speech="minus">−</mo><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="29" data-semantic-parent="36" data-semantic-speech="y">y</mi><mo data-semantic-type="operator" data-semantic-role="subtraction" data-semantic-id="30" data-semantic-parent="36" data-semantic-operator="infixop,−" data-semantic-speech="minus">−</mo><mrow data-semantic-type="infixop" data-semantic-role="implicit" data-semantic-annotation="clearspeak:simple;clearspeak:unit;clearspeak:simple;clearspeak:unit" data-semantic-id="38" data-semantic-children="31,32" data-semantic-content="37" data-semantic-parent="36" data-semantic-speech="x z"><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="31" data-semantic-parent="38" data-semantic-speech="x">x</mi><mo data-semantic-type="operator" data-semantic-role="multiplication" data-semantic-id="37" data-semantic-parent="38" data-semantic-added="true" data-semantic-operator="infixop,⁢" data-semantic-speech="times">⁢</mo><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="32" data-semantic-parent="38" data-semantic-speech="z">z</mi></mrow></mrow></mrow></mtd></mtr><mtr data-semantic-type="row" data-semantic-role="table" data-semantic-id="63" data-semantic-children="45,62" data-semantic-parent="64" data-semantic-speech="1st Column ModifyingAbove z With dot 2nd Column equals minus beta z plus x y" data-semantic-prefix="3rd Row"><mtd data-semantic-type="cell" data-semantic-role="table" data-semantic-id="45" data-semantic-children="44" data-semantic-parent="63" data-semantic-speech="ModifyingAbove z With dot" data-semantic-prefix="1st Column"><mrow class="MJX-TeXAtom-ORD"><mover data-semantic-type="overscore" data-semantic-role="latinletter" data-semantic-id="44" data-semantic-children="42,43" data-semantic-parent="45" data-semantic-speech="ModifyingAbove z With dot"><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="42" data-semantic-parent="44" data-semantic-speech="z" data-semantic-prefix="Base">z</mi><mo data-semantic-type="operator" data-semantic-role="overaccent" data-semantic-id="43" data-semantic-parent="44" data-semantic-speech="dot" data-semantic-prefix="Overscript">˙</mo></mover></mrow></mtd><mtd data-semantic-type="cell" data-semantic-role="table" data-semantic-id="62" data-semantic-children="61" data-semantic-parent="63" data-semantic-speech="equals minus beta z plus x y" data-semantic-prefix="2nd Column"><mi/><mrow data-semantic-type="relseq" data-semantic-role="equality" data-semantic-id="61" data-semantic-children="54,60" data-semantic-content="47" data-semantic-parent="62" data-semantic-speech="equals minus beta z plus x y"><mrow data-semantic-type="empty" data-semantic-role="unknown" data-semantic-id="54" data-semantic-parent="61" data-semantic-speech=""/><mo data-semantic-type="relation" data-semantic-role="equality" data-semantic-id="47" data-semantic-parent="61" data-semantic-operator="relseq,=" data-semantic-speech="equals">=</mo><mrow data-semantic-type="infixop" data-semantic-role="addition" data-semantic-id="60" data-semantic-children="57,59" data-semantic-content="51" data-semantic-parent="61" data-semantic-speech="minus beta z plus x y"><mrow data-semantic-type="prefixop" data-semantic-role="negative" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="57" data-semantic-children="56" data-semantic-content="48" data-semantic-parent="60" data-semantic-speech="minus beta z"><mo data-semantic-type="operator" data-semantic-role="subtraction" data-semantic-id="48" data-semantic-parent="57" data-semantic-operator="prefixop,−" data-semantic-speech="minus">−</mo><mrow data-semantic-type="infixop" data-semantic-role="implicit" data-semantic-annotation="clearspeak:simple;clearspeak:unit;clearspeak:simple;clearspeak:unit" data-semantic-id="56" data-semantic-children="49,50" data-semantic-content="55" data-semantic-parent="57" data-semantic-speech="beta z"><mi data-semantic-type="identifier" data-semantic-role="greekletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="49" data-semantic-parent="56" data-semantic-speech="beta">β</mi><mo data-semantic-type="operator" data-semantic-role="multiplication" data-semantic-id="55" data-semantic-parent="56" data-semantic-added="true" data-semantic-operator="infixop,⁢" data-semantic-speech="times">⁢</mo><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="50" data-semantic-parent="56" data-semantic-speech="z">z</mi></mrow></mrow><mo data-semantic-type="operator" data-semantic-role="addition" data-semantic-id="51" data-semantic-parent="60" data-semantic-operator="infixop,+" data-semantic-speech="plus">+</mo><mrow data-semantic-type="infixop" data-semantic-role="implicit" data-semantic-annotation="clearspeak:simple;clearspeak:unit;clearspeak:simple;clearspeak:unit" data-semantic-id="59" data-semantic-children="52,53" data-semantic-content="58" data-semantic-parent="60" data-semantic-speech="x y"><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="52" data-semantic-parent="59" data-semantic-speech="x">x</mi><mo data-semantic-type="operator" data-semantic-role="multiplication" data-semantic-id="58" data-semantic-parent="59" data-semantic-added="true" data-semantic-operator="infixop,⁢" data-semantic-speech="times">⁢</mo><mi data-semantic-type="identifier" data-semantic-role="latinletter" data-semantic-font="italic" data-semantic-annotation="clearspeak:simple;clearspeak:simple" data-semantic-id="53" data-semantic-parent="59" data-semantic-speech="y">y</mi></mrow></mrow></mrow></mtd></mtr></mtable></math>
```

which e.g., using direct/mml2svg or direct/mml2chtml gives

```
mj3-demos-node/node_modules/mathjax3/mathjax3/core/MathDocument.js:164
            finally { if (e_4) throw e_4.error; }
                               ^
Error: Unknown node type "mi/"
    at MathMLCompile.error (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:217:15)
    at MathMLCompile.makeNode (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:65:49)
    at MathMLCompile.addChildren (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:125:57)
    at MathMLCompile.makeNode (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:72:14)
    at MathMLCompile.addChildren (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:125:57)
    at MathMLCompile.makeNode (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:72:14)
    at MathMLCompile.addChildren (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:125:57)
    at MathMLCompile.makeNode (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:72:14)
    at MathMLCompile.addChildren (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:125:57)
    at MathMLCompile.makeNode (mj3-demos-node/node_modules/mathjax3/mathjax3/input/mathml/MathMLCompile.js:72:14)
```

**Comment by pkra** [comment]
Thanks for tracking this down.
